### ISSUE TITLE
Feat: Batch remove temporary files of faulty processed data folders

### ISSUE THREAD

**Issue by josefyu** [QIMP-Team/MOOSE-v0.1.0#29]
When MOOSE fails to infer the dataset, the command is stopped and the folders are left with temporary files given in this structure:

Newly created folders: CT, PT, labels, stats, temp and 2 .JSON files.

In order to clean these datasets and make them executable again, it would be nice to have a command to revert them into their original states. The command which can manually be used is listed here.

`root@meta-zoo:/home/mz/Documents/Projects/"Work-Directory"/faulty# find -maxdepth 2 -name CT -exec rm -rf {} \;`
`root@meta-zoo:/home/mz/Documents/Projects/"Work-Directory"/faulty# find -maxdepth 2 -name PT -exec rm -rf {} \;`
`root@meta-zoo:/home/mz/Documents/Projects/"Work-Directory"/faulty# find -maxdepth 2 -name labels -exec rm -rf {} \;`
`root@meta-zoo:/home/mz/Documents/Projects/"Work-Directory"/faulty# find -maxdepth 2 -name temp -exec rm -rf {} \;`
`root@meta-zoo:/home/mz/Documents/Projects/"Work-Directory"/faulty# find -maxdepth 2 -name stats -exec rm -rf {} \;`

**Comment by LalithShiyam** [comment]
﻿Hi, I don’t think this is needed. This is just too much. Kindly delete it manually. This request won’t be implemented.
